name: wordwizzard
description: "An application that supports users in learning English vocabulary in flashcard format."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.5.0
  convex_bottom_bar: ^3.2.0
  fl_chart: ^0.67.0
  flex_color_scheme: ^7.3.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  google_fonts: 6.1.0
  http: ^1.2.1
  intl: ^0.18.1
  introduction_screen: ^3.1.12
  jwt_decoder: ^2.0.1
  lottie: ^3.1.0
  modal_bottom_sheet: ^3.0.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  tab_container: ^3.3.1
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo-removebg.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo/logo-removebg.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/logo-removebg.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo/logo-removebg.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo/logo.png
  - assets/images/logo/logo-removebg.png
  - assets/images/otp_verify/otp_verify_img.svg
  - assets/icon/facebook.svg
  - assets/icon/apple.svg
  - assets/icon/google.svg
  - lib/lang/vi.json
  - lib/lang/en.json
  - assets/images/forget_pass/forget_pass.svg
  - assets/images/reset_pass/reset_pass.svg
  - assets/images/intro/online_test.svg
  - assets/images/intro/research_paper.svg
  - assets/images/intro/studying.svg
  - assets/images/banner/banner.png
  - assets/images/avatar/avatar.svg
  - assets/animation/loading.json
  - assets/animation/empty_ani.json
  - assets/animation/tick_ani.json