name: wordwizzard
description: "An application that supports users in learning English vocabulary in flashcard format."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  google_fonts: 6.1.0
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/intro/intro.png
  - lib/lang/vi.json
  - lib/lang/en.json